//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Rockend.WebAccess.Common.ClientMessage;
using Rockend.WebAccess.RockendMessage;

namespace ServiceReference1
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ServiceReference1.IRequestService")]
    public interface IRequestService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRequestService/Process", ReplyAction = "http://tempuri.org/IRequestService/ProcessResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<ServiceReference1.ProcessResponse> ProcessAsync(ServiceReference1.ProcessRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRequestService/ProcessStrata", ReplyAction = "http://tempuri.org/IRequestService/ProcessStrataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<ServiceReference1.ProcessStrataResponse> ProcessStrataAsync(ServiceReference1.ProcessStrataRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRequestService/ProcessRequest", ReplyAction = "http://tempuri.org/IRequestService/ProcessRequestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<ServiceReference1.ProcessRequestResponse> ProcessRequestAsync(ServiceReference1.ProcessRequestRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRequestService/PostResponse", ReplyAction = "http://tempuri.org/IRequestService/PostResponseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<ServiceReference1.PostResponseResponse> PostResponseAsync(ServiceReference1.PostResponseRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRequestService/VersionCheck", ReplyAction = "http://tempuri.org/IRequestService/VersionCheckResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<ServiceReference1.VersionCheckResponse1> VersionCheckAsync(ServiceReference1.VersionCheckRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRequestService/GetAgencyGuidAndSetRWACVersion", ReplyAction = "http://tempuri.org/IRequestService/GetAgencyGuidAndSetRWACVersionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<ServiceReference1.GetAgencyGuidAndSetRWACVersionResponse> GetAgencyGuidAndSetRWACVersionAsync(ServiceReference1.GetAgencyGuidAndSetRWACVersionRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRequestService/GetAgencyGUID", ReplyAction = "http://tempuri.org/IRequestService/GetAgencyGUIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<ServiceReference1.GetAgencyGUIDResponse> GetAgencyGUIDAsync(ServiceReference1.GetAgencyGUIDRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRequestService/UpdateClientSchedules", ReplyAction = "http://tempuri.org/IRequestService/UpdateClientSchedulesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<ServiceReference1.UpdateClientSchedulesResponse> UpdateClientSchedulesAsync(ServiceReference1.UpdateClientSchedulesRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRequestService/GetProcessor", ReplyAction = "http://tempuri.org/IRequestService/GetProcessorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<ServiceReference1.GetProcessorResponse> GetProcessorAsync(ServiceReference1.GetProcessorRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRequestService/CheckProcessor", ReplyAction = "http://tempuri.org/IRequestService/CheckProcessorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<ServiceReference1.CheckProcessorResponse> CheckProcessorAsync(ServiceReference1.CheckProcessorRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRequestService/RegisterAgencyListener", ReplyAction = "http://tempuri.org/IRequestService/RegisterAgencyListenerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<ServiceReference1.RegisterAgencyListenerResponse> RegisterAgencyListenerAsync(ServiceReference1.RegisterAgencyListenerRequest request);
    }
    /*
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StrataMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Rockend.WebAccess.RockendMessage")]
    public partial class RockendRequest
    {
        
        private string actionNameField;
        
        private string applicationCodeField;
        
        private int applicationKeyField;
        
        private bool applicationKeyFieldSpecified;
        
        private string bodyXmlField;
        
        private int serviceKeyField;
        
        private bool serviceKeyFieldSpecified;
        
        private string servicePasswordField;
        
        private string sessionIDField;
        
        private int timeoutMSField;
        
        private bool timeoutMSFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ActionName
        {
            get
            {
                return this.actionNameField;
            }
            set
            {
                this.actionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ApplicationCode
        {
            get
            {
                return this.applicationCodeField;
            }
            set
            {
                this.applicationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ApplicationKey
        {
            get
            {
                return this.applicationKeyField;
            }
            set
            {
                this.applicationKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApplicationKeySpecified
        {
            get
            {
                return this.applicationKeyFieldSpecified;
            }
            set
            {
                this.applicationKeyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string BodyXml
        {
            get
            {
                return this.bodyXmlField;
            }
            set
            {
                this.bodyXmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ServiceKey
        {
            get
            {
                return this.serviceKeyField;
            }
            set
            {
                this.serviceKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServiceKeySpecified
        {
            get
            {
                return this.serviceKeyFieldSpecified;
            }
            set
            {
                this.serviceKeyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ServicePassword
        {
            get
            {
                return this.servicePasswordField;
            }
            set
            {
                this.servicePasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string SessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TimeoutMS
        {
            get
            {
                return this.timeoutMSField;
            }
            set
            {
                this.timeoutMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeoutMSSpecified
        {
            get
            {
                return this.timeoutMSFieldSpecified;
            }
            set
            {
                this.timeoutMSFieldSpecified = value;
            }
        }
    }*/

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.RockendMessage")]
    public partial class AppKeyMachine
    {

        private int appKeyField;

        private bool appKeyFieldSpecified;

        private int appVersionField;

        private bool appVersionFieldSpecified;

        private int appmhVersionField;

        private bool appmhVersionFieldSpecified;

        private string machineNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int AppKey
        {
            get
            {
                return this.appKeyField;
            }
            set
            {
                this.appKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AppKeySpecified
        {
            get
            {
                return this.appKeyFieldSpecified;
            }
            set
            {
                this.appKeyFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public int AppVersion
        {
            get
            {
                return this.appVersionField;
            }
            set
            {
                this.appVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AppVersionSpecified
        {
            get
            {
                return this.appVersionFieldSpecified;
            }
            set
            {
                this.appVersionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public int AppmhVersion
        {
            get
            {
                return this.appmhVersionField;
            }
            set
            {
                this.appmhVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AppmhVersionSpecified
        {
            get
            {
                return this.appmhVersionFieldSpecified;
            }
            set
            {
                this.appmhVersionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
        public string MachineName
        {
            get
            {
                return this.machineNameField;
            }
            set
            {
                this.machineNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.RockendMessage")]
    public partial class GetMessageRequest
    {

        private string agencyGuidField;

        private int amhVersionField;

        private bool amhVersionFieldSpecified;

        private AppKeyMachine[] appKeyMachineListField;

        private int[] applicationKeyListField;

        private string machineNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string AgencyGuid
        {
            get
            {
                return this.agencyGuidField;
            }
            set
            {
                this.agencyGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public int AmhVersion
        {
            get
            {
                return this.amhVersionField;
            }
            set
            {
                this.amhVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmhVersionSpecified
        {
            get
            {
                return this.amhVersionFieldSpecified;
            }
            set
            {
                this.amhVersionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 2)]
        public AppKeyMachine[] AppKeyMachineList
        {
            get
            {
                return this.appKeyMachineListField;
            }
            set
            {
                this.appKeyMachineListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable = false)]
        public int[] ApplicationKeyList
        {
            get
            {
                return this.applicationKeyListField;
            }
            set
            {
                this.applicationKeyListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public string MachineName
        {
            get
            {
                return this.machineNameField;
            }
            set
            {
                this.machineNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.Common.ClientMessage")]
    public partial class FileCheckResponse
    {

        private bool okField;

        private bool okFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public bool OK
        {
            get
            {
                return this.okField;
            }
            set
            {
                this.okField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OKSpecified
        {
            get
            {
                return this.okFieldSpecified;
            }
            set
            {
                this.okFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.Common.ClientMessage")]
    public partial class FileCheckRequest
    {

        private string fileNameField;

        private long filesizeField;

        private bool filesizeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public long Filesize
        {
            get
            {
                return this.filesizeField;
            }
            set
            {
                this.filesizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FilesizeSpecified
        {
            get
            {
                return this.filesizeFieldSpecified;
            }
            set
            {
                this.filesizeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.Common.ClientMessage")]
    public partial class DownloadFileResponse
    {

        private Exception errorField;

        private byte[] fileContentField;

        private string fileNameField;

        private bool successField;

        private bool successFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public Exception Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", IsNullable = true, Order = 1)]
        public byte[] FileContent
        {
            get
            {
                return this.fileContentField;
            }
            set
            {
                this.fileContentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified
        {
            get
            {
                return this.successFieldSpecified;
            }
            set
            {
                this.successFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/System")]
    public partial class Exception
    {

        private System.Xml.Linq.XElement[] anyField;

        private System.Xml.XmlQualifiedName factoryTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace = "", Order = 0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://schemas.microsoft.com/2003/10/Serialization/")]
        public System.Xml.XmlQualifiedName FactoryType
        {
            get
            {
                return this.factoryTypeField;
            }
            set
            {
                this.factoryTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.Common")]
    public partial class UpdateResponse
    {

        private Exception errorField;

        private bool isOkField;

        private bool isOkFieldSpecified;

        private string resultField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public Exception Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public bool IsOk
        {
            get
            {
                return this.isOkField;
            }
            set
            {
                this.isOkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsOkSpecified
        {
            get
            {
                return this.isOkFieldSpecified;
            }
            set
            {
                this.isOkFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2005/08/addressing")]
    public partial class MetadataType
    {

        private System.Xml.Linq.XElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2005/08/addressing")]
    public partial class ReferenceParametersType
    {

        private System.Xml.Linq.XElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2005/08/addressing")]
    public partial class AttributedURIType
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "anyURI")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2005/08/addressing")]
    public partial class EndpointReferenceType
    {

        private AttributedURIType addressField;

        private ReferenceParametersType referenceParametersField;

        private MetadataType metadataField;

        private System.Xml.Linq.XElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public AttributedURIType Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ReferenceParametersType ReferenceParameters
        {
            get
            {
                return this.referenceParametersField;
            }
            set
            {
                this.referenceParametersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public MetadataType Metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 3)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.Common.Transport")]
    public partial class RockendApplication
    {

        private string agencyGUIDField;

        private string agencyNameField;

        private string applicationCodeField;

        private int applicationKeyField;

        private bool applicationKeyFieldSpecified;

        private int appmhVersionField;

        private bool appmhVersionFieldSpecified;

        private int dataSourceIDField;

        private bool dataSourceIDFieldSpecified;

        private string descriptionField;

        private EndpointReferenceType endPointField;

        private bool isActiveField;

        private bool isActiveFieldSpecified;

        private bool isDataLocalField;

        private bool isDataLocalFieldSpecified;

        private string machineNameField;

        private int rWACVersionField;

        private bool rWACVersionFieldSpecified;

        private string serialNumberField;

        private int versionField;

        private bool versionFieldSpecified;

        private bool webEnabledField;

        private bool webEnabledFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string AgencyGUID
        {
            get
            {
                return this.agencyGUIDField;
            }
            set
            {
                this.agencyGUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string AgencyName
        {
            get
            {
                return this.agencyNameField;
            }
            set
            {
                this.agencyNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string ApplicationCode
        {
            get
            {
                return this.applicationCodeField;
            }
            set
            {
                this.applicationCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public int ApplicationKey
        {
            get
            {
                return this.applicationKeyField;
            }
            set
            {
                this.applicationKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApplicationKeySpecified
        {
            get
            {
                return this.applicationKeyFieldSpecified;
            }
            set
            {
                this.applicationKeyFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public int AppmhVersion
        {
            get
            {
                return this.appmhVersionField;
            }
            set
            {
                this.appmhVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AppmhVersionSpecified
        {
            get
            {
                return this.appmhVersionFieldSpecified;
            }
            set
            {
                this.appmhVersionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public int DataSourceID
        {
            get
            {
                return this.dataSourceIDField;
            }
            set
            {
                this.dataSourceIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataSourceIDSpecified
        {
            get
            {
                return this.dataSourceIDFieldSpecified;
            }
            set
            {
                this.dataSourceIDFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 6)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 7)]
        public EndpointReferenceType EndPoint
        {
            get
            {
                return this.endPointField;
            }
            set
            {
                this.endPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public bool IsActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsActiveSpecified
        {
            get
            {
                return this.isActiveFieldSpecified;
            }
            set
            {
                this.isActiveFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public bool IsDataLocal
        {
            get
            {
                return this.isDataLocalField;
            }
            set
            {
                this.isDataLocalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDataLocalSpecified
        {
            get
            {
                return this.isDataLocalFieldSpecified;
            }
            set
            {
                this.isDataLocalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 10)]
        public string MachineName
        {
            get
            {
                return this.machineNameField;
            }
            set
            {
                this.machineNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public int RWACVersion
        {
            get
            {
                return this.rWACVersionField;
            }
            set
            {
                this.rWACVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RWACVersionSpecified
        {
            get
            {
                return this.rWACVersionFieldSpecified;
            }
            set
            {
                this.rWACVersionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 12)]
        public string SerialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public int Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VersionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public bool WebEnabled
        {
            get
            {
                return this.webEnabledField;
            }
            set
            {
                this.webEnabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WebEnabledSpecified
        {
            get
            {
                return this.webEnabledFieldSpecified;
            }
            set
            {
                this.webEnabledFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.Common.Transport")]
    public partial class AgencyGuidRequest
    {

        private RockendApplication[] applicationsField;

        private int rWACVersionField;

        private bool rWACVersionFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 0)]
        public RockendApplication[] Applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public int RWACVersion
        {
            get
            {
                return this.rWACVersionField;
            }
            set
            {
                this.rWACVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RWACVersionSpecified
        {
            get
            {
                return this.rWACVersionFieldSpecified;
            }
            set
            {
                this.rWACVersionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.Common")]
    public partial class VersionCheckResponse
    {

        private bool isUpdateRequiredField;

        private bool isUpdateRequiredFieldSpecified;

        private string newVersionField;

        private byte[] zipFileField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public bool IsUpdateRequired
        {
            get
            {
                return this.isUpdateRequiredField;
            }
            set
            {
                this.isUpdateRequiredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsUpdateRequiredSpecified
        {
            get
            {
                return this.isUpdateRequiredFieldSpecified;
            }
            set
            {
                this.isUpdateRequiredFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string NewVersion
        {
            get
            {
                return this.newVersionField;
            }
            set
            {
                this.newVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", IsNullable = true, Order = 2)]
        public byte[] ZipFile
        {
            get
            {
                return this.zipFileField;
            }
            set
            {
                this.zipFileField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.Common")]
    public partial class VersionCheckRequest
    {

        private string applicationCodeField;

        private string dBVersionField;

        private int majorVersionField;

        private bool majorVersionFieldSpecified;

        private int minorVersionField;

        private bool minorVersionFieldSpecified;

        private string softwareVersionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string ApplicationCode
        {
            get
            {
                return this.applicationCodeField;
            }
            set
            {
                this.applicationCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string DBVersion
        {
            get
            {
                return this.dBVersionField;
            }
            set
            {
                this.dBVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public int MajorVersion
        {
            get
            {
                return this.majorVersionField;
            }
            set
            {
                this.majorVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MajorVersionSpecified
        {
            get
            {
                return this.majorVersionFieldSpecified;
            }
            set
            {
                this.majorVersionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public int MinorVersion
        {
            get
            {
                return this.minorVersionField;
            }
            set
            {
                this.minorVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinorVersionSpecified
        {
            get
            {
                return this.minorVersionFieldSpecified;
            }
            set
            {
                this.minorVersionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public string SoftwareVersion
        {
            get
            {
                return this.softwareVersionField;
            }
            set
            {
                this.softwareVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.RockendMessage")]
    public partial class ApplicationResponse
    {

        private string applicationCodeField;

        private int applicationKeyField;

        private bool applicationKeyFieldSpecified;

        private string dataField;

        private string requestIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string ApplicationCode
        {
            get
            {
                return this.applicationCodeField;
            }
            set
            {
                this.applicationCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public int ApplicationKey
        {
            get
            {
                return this.applicationKeyField;
            }
            set
            {
                this.applicationKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApplicationKeySpecified
        {
            get
            {
                return this.applicationKeyFieldSpecified;
            }
            set
            {
                this.applicationKeyFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.RockendMessage")]
    public partial class ApplicationRequest
    {

        private string actionNameField;

        private string applicationCodeField;

        private int applicationKeyField;

        private bool applicationKeyFieldSpecified;

        private string assemblyNameField;

        private string bodyXmlField;

        private string classNameField;

        private bool isErrorField;

        private bool isErrorFieldSpecified;

        private bool isTimeoutResponseField;

        private bool isTimeoutResponseFieldSpecified;

        private bool oneWayField;

        private bool oneWayFieldSpecified;

        private string requestIDField;

        private int serviceKeyField;

        private bool serviceKeyFieldSpecified;

        private string servicePasswordField;

        private string sessionIDField;

        private int timeoutMSField;

        private bool timeoutMSFieldSpecified;

        private string deviceTypeField;

        private string appVersionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string ActionName
        {
            get
            {
                return this.actionNameField;
            }
            set
            {
                this.actionNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string ApplicationCode
        {
            get
            {
                return this.applicationCodeField;
            }
            set
            {
                this.applicationCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public int ApplicationKey
        {
            get
            {
                return this.applicationKeyField;
            }
            set
            {
                this.applicationKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApplicationKeySpecified
        {
            get
            {
                return this.applicationKeyFieldSpecified;
            }
            set
            {
                this.applicationKeyFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
        public string AssemblyName
        {
            get
            {
                return this.assemblyNameField;
            }
            set
            {
                this.assemblyNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public string BodyXml
        {
            get
            {
                return this.bodyXmlField;
            }
            set
            {
                this.bodyXmlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 5)]
        public string ClassName
        {
            get
            {
                return this.classNameField;
            }
            set
            {
                this.classNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public bool IsError
        {
            get
            {
                return this.isErrorField;
            }
            set
            {
                this.isErrorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsErrorSpecified
        {
            get
            {
                return this.isErrorFieldSpecified;
            }
            set
            {
                this.isErrorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public bool IsTimeoutResponse
        {
            get
            {
                return this.isTimeoutResponseField;
            }
            set
            {
                this.isTimeoutResponseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsTimeoutResponseSpecified
        {
            get
            {
                return this.isTimeoutResponseFieldSpecified;
            }
            set
            {
                this.isTimeoutResponseFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public bool OneWay
        {
            get
            {
                return this.oneWayField;
            }
            set
            {
                this.oneWayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OneWaySpecified
        {
            get
            {
                return this.oneWayFieldSpecified;
            }
            set
            {
                this.oneWayFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public int ServiceKey
        {
            get
            {
                return this.serviceKeyField;
            }
            set
            {
                this.serviceKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServiceKeySpecified
        {
            get
            {
                return this.serviceKeyFieldSpecified;
            }
            set
            {
                this.serviceKeyFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 11)]
        public string ServicePassword
        {
            get
            {
                return this.servicePasswordField;
            }
            set
            {
                this.servicePasswordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 12)]
        public string SessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public int TimeoutMS
        {
            get
            {
                return this.timeoutMSField;
            }
            set
            {
                this.timeoutMSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeoutMSSpecified
        {
            get
            {
                return this.timeoutMSFieldSpecified;
            }
            set
            {
                this.timeoutMSFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 14)]
        public string DeviceType
        {
            get
            {
                return this.deviceTypeField;
            }
            set
            {
                this.deviceTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 15)]
        public string AppVersion
        {
            get
            {
                return this.appVersionField;
            }
            set
            {
                this.appVersionField = value;
            }
        }
    }
    /*
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StrataMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.Common.ClientMessage")]
    public partial class MessageRequest : RockendRequest
    {

        private string[] activatedMachinesField;

        private string agencyGUIDField;

        private string assemblyNameField;

        private string classNameField;

        private bool isTimeoutResponseField;

        private bool isTimeoutResponseFieldSpecified;

        private bool oneWayField;

        private bool oneWayFieldSpecified;

        private string requestIDField;

        private string deviceTypeField;

        private string appVersionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] ActivatedMachines
        {
            get
            {
                return this.activatedMachinesField;
            }
            set
            {
                this.activatedMachinesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string AgencyGUID
        {
            get
            {
                return this.agencyGUIDField;
            }
            set
            {
                this.agencyGUIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string AssemblyName
        {
            get
            {
                return this.assemblyNameField;
            }
            set
            {
                this.assemblyNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
        public string ClassName
        {
            get
            {
                return this.classNameField;
            }
            set
            {
                this.classNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public bool IsTimeoutResponse
        {
            get
            {
                return this.isTimeoutResponseField;
            }
            set
            {
                this.isTimeoutResponseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsTimeoutResponseSpecified
        {
            get
            {
                return this.isTimeoutResponseFieldSpecified;
            }
            set
            {
                this.isTimeoutResponseFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public bool OneWay
        {
            get
            {
                return this.oneWayField;
            }
            set
            {
                this.oneWayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OneWaySpecified
        {
            get
            {
                return this.oneWayFieldSpecified;
            }
            set
            {
                this.oneWayFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 7)]
        public string DeviceType
        {
            get
            {
                return this.deviceTypeField;
            }
            set
            {
                this.deviceTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 8)]
        public string AppVersion
        {
            get
            {
                return this.appVersionField;
            }
            set
            {
                this.appVersionField = value;
            }
        }
    }
    */
    /*
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.Common.ClientMessage")]
    public partial class StrataMessage : MessageRequest
    {

        private int contactIDField;

        private bool contactIDFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int ContactID
        {
            get
            {
                return this.contactIDField;
            }
            set
            {
                this.contactIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContactIDSpecified
        {
            get
            {
                return this.contactIDFieldSpecified;
            }
            set
            {
                this.contactIDFieldSpecified = value;
            }
        }
    }
    */
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "Process", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ProcessRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public RockendRequest request;

        public ProcessRequest()
        {
        }

        public ProcessRequest(RockendRequest request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ProcessResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ProcessResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public MessageRequest ProcessResult;

        public ProcessResponse()
        {
        }

        public ProcessResponse(MessageRequest ProcessResult)
        {
            this.ProcessResult = ProcessResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ProcessStrata", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ProcessStrataRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public StrataMessage request;

        public ProcessStrataRequest()
        {
        }

        public ProcessStrataRequest(StrataMessage request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ProcessStrataResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ProcessStrataResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public MessageRequest ProcessStrataResult;

        public ProcessStrataResponse()
        {
        }

        public ProcessStrataResponse(MessageRequest ProcessStrataResult)
        {
            this.ProcessStrataResult = ProcessStrataResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ProcessRequest", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ProcessRequestRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ServiceReference1.ApplicationRequest request;

        public ProcessRequestRequest()
        {
        }

        public ProcessRequestRequest(ServiceReference1.ApplicationRequest request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ProcessRequestResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ProcessRequestResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ServiceReference1.ApplicationResponse ProcessRequestResult;

        public ProcessRequestResponse()
        {
        }

        public ProcessRequestResponse(ServiceReference1.ApplicationResponse ProcessRequestResult)
        {
            this.ProcessRequestResult = ProcessRequestResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "PostResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class PostResponseRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public MessageRequest response;

        public PostResponseRequest()
        {
        }

        public PostResponseRequest(MessageRequest response)
        {
            this.response = response;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "PostResponseResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class PostResponseResponse
    {

        public PostResponseResponse()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "VersionCheck", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class VersionCheckRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ServiceReference1.VersionCheckRequest version;

        public VersionCheckRequest1()
        {
        }

        public VersionCheckRequest1(ServiceReference1.VersionCheckRequest version)
        {
            this.version = version;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "VersionCheckResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class VersionCheckResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ServiceReference1.VersionCheckResponse VersionCheckResult;

        public VersionCheckResponse1()
        {
        }

        public VersionCheckResponse1(ServiceReference1.VersionCheckResponse VersionCheckResult)
        {
            this.VersionCheckResult = VersionCheckResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAgencyGuidAndSetRWACVersion", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetAgencyGuidAndSetRWACVersionRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ServiceReference1.AgencyGuidRequest applicationKeys;

        public GetAgencyGuidAndSetRWACVersionRequest()
        {
        }

        public GetAgencyGuidAndSetRWACVersionRequest(ServiceReference1.AgencyGuidRequest applicationKeys)
        {
            this.applicationKeys = applicationKeys;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAgencyGuidAndSetRWACVersionResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetAgencyGuidAndSetRWACVersionResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.Common.Transport")]
        public ServiceReference1.RockendApplication[] GetAgencyGuidAndSetRWACVersionResult;

        public GetAgencyGuidAndSetRWACVersionResponse()
        {
        }

        public GetAgencyGuidAndSetRWACVersionResponse(ServiceReference1.RockendApplication[] GetAgencyGuidAndSetRWACVersionResult)
        {
            this.GetAgencyGuidAndSetRWACVersionResult = GetAgencyGuidAndSetRWACVersionResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAgencyGUID", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetAgencyGUIDRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.Common.Transport")]
        public ServiceReference1.RockendApplication[] applicationKeys;

        public GetAgencyGUIDRequest()
        {
        }

        public GetAgencyGUIDRequest(ServiceReference1.RockendApplication[] applicationKeys)
        {
            this.applicationKeys = applicationKeys;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAgencyGUIDResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetAgencyGUIDResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.Common.Transport")]
        public ServiceReference1.RockendApplication[] GetAgencyGUIDResult;

        public GetAgencyGUIDResponse()
        {
        }

        public GetAgencyGUIDResponse(ServiceReference1.RockendApplication[] GetAgencyGUIDResult)
        {
            this.GetAgencyGUIDResult = GetAgencyGUIDResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateClientSchedules", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class UpdateClientSchedulesRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable = false)]
        public int[] applicationKeys;

        public UpdateClientSchedulesRequest()
        {
        }

        public UpdateClientSchedulesRequest(int[] applicationKeys)
        {
            this.applicationKeys = applicationKeys;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateClientSchedulesResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class UpdateClientSchedulesResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ServiceReference1.UpdateResponse UpdateClientSchedulesResult;

        public UpdateClientSchedulesResponse()
        {
        }

        public UpdateClientSchedulesResponse(ServiceReference1.UpdateResponse UpdateClientSchedulesResult)
        {
            this.UpdateClientSchedulesResult = UpdateClientSchedulesResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetProcessor", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetProcessorRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string assemblyName;

        public GetProcessorRequest()
        {
        }

        public GetProcessorRequest(string assemblyName)
        {
            this.assemblyName = assemblyName;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetProcessorResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetProcessorResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ServiceReference1.DownloadFileResponse GetProcessorResult;

        public GetProcessorResponse()
        {
        }

        public GetProcessorResponse(ServiceReference1.DownloadFileResponse GetProcessorResult)
        {
            this.GetProcessorResult = GetProcessorResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckProcessor", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class CheckProcessorRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ServiceReference1.FileCheckRequest request;

        public CheckProcessorRequest()
        {
        }

        public CheckProcessorRequest(ServiceReference1.FileCheckRequest request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckProcessorResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class CheckProcessorResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ServiceReference1.FileCheckResponse CheckProcessorResult;

        public CheckProcessorResponse()
        {
        }

        public CheckProcessorResponse(ServiceReference1.FileCheckResponse CheckProcessorResult)
        {
            this.CheckProcessorResult = CheckProcessorResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RegisterAgencyListener", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class RegisterAgencyListenerRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ServiceReference1.GetMessageRequest amhListenerRequest;

        public RegisterAgencyListenerRequest()
        {
        }

        public RegisterAgencyListenerRequest(ServiceReference1.GetMessageRequest amhListenerRequest)
        {
            this.amhListenerRequest = amhListenerRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RegisterAgencyListenerResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class RegisterAgencyListenerResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Rockend.WebAccess.Common.ClientMessage")]
        public MessageRequest[] RegisterAgencyListenerResult;

        public RegisterAgencyListenerResponse()
        {
        }

        public RegisterAgencyListenerResponse(MessageRequest[] RegisterAgencyListenerResult)
        {
            this.RegisterAgencyListenerResult = RegisterAgencyListenerResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IRequestServiceChannel : ServiceReference1.IRequestService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class RequestServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IRequestService>, ServiceReference1.IRequestService
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public RequestServiceClient() :
                base(RequestServiceClient.GetDefaultBinding(), RequestServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IRequestService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public RequestServiceClient(EndpointConfiguration endpointConfiguration) :
                base(RequestServiceClient.GetBindingForEndpoint(endpointConfiguration), RequestServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public RequestServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(RequestServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public RequestServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(RequestServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public RequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ProcessResponse> ServiceReference1.IRequestService.ProcessAsync(ServiceReference1.ProcessRequest request)
        {
            return base.Channel.ProcessAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.ProcessResponse> ProcessAsync(RockendRequest request)
        {
            ServiceReference1.ProcessRequest inValue = new ServiceReference1.ProcessRequest();
            inValue.request = request;
            return ((ServiceReference1.IRequestService)(this)).ProcessAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ProcessStrataResponse> ServiceReference1.IRequestService.ProcessStrataAsync(ServiceReference1.ProcessStrataRequest request)
        {
            return base.Channel.ProcessStrataAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.ProcessStrataResponse> ProcessStrataAsync(StrataMessage request)
        {
            ServiceReference1.ProcessStrataRequest inValue = new ServiceReference1.ProcessStrataRequest();
            inValue.request = request;
            return ((ServiceReference1.IRequestService)(this)).ProcessStrataAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ProcessRequestResponse> ServiceReference1.IRequestService.ProcessRequestAsync(ServiceReference1.ProcessRequestRequest request)
        {
            return base.Channel.ProcessRequestAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.ProcessRequestResponse> ProcessRequestAsync(ServiceReference1.ApplicationRequest request)
        {
            ServiceReference1.ProcessRequestRequest inValue = new ServiceReference1.ProcessRequestRequest();
            inValue.request = request;
            return ((ServiceReference1.IRequestService)(this)).ProcessRequestAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.PostResponseResponse> ServiceReference1.IRequestService.PostResponseAsync(ServiceReference1.PostResponseRequest request)
        {
            return base.Channel.PostResponseAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.PostResponseResponse> PostResponseAsync(MessageRequest response)
        {
            ServiceReference1.PostResponseRequest inValue = new ServiceReference1.PostResponseRequest();
            inValue.response = response;
            return ((ServiceReference1.IRequestService)(this)).PostResponseAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.VersionCheckResponse1> ServiceReference1.IRequestService.VersionCheckAsync(ServiceReference1.VersionCheckRequest1 request)
        {
            return base.Channel.VersionCheckAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.VersionCheckResponse1> VersionCheckAsync(ServiceReference1.VersionCheckRequest version)
        {
            ServiceReference1.VersionCheckRequest1 inValue = new ServiceReference1.VersionCheckRequest1();
            inValue.version = version;
            return ((ServiceReference1.IRequestService)(this)).VersionCheckAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetAgencyGuidAndSetRWACVersionResponse> ServiceReference1.IRequestService.GetAgencyGuidAndSetRWACVersionAsync(ServiceReference1.GetAgencyGuidAndSetRWACVersionRequest request)
        {
            return base.Channel.GetAgencyGuidAndSetRWACVersionAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.GetAgencyGuidAndSetRWACVersionResponse> GetAgencyGuidAndSetRWACVersionAsync(ServiceReference1.AgencyGuidRequest applicationKeys)
        {
            ServiceReference1.GetAgencyGuidAndSetRWACVersionRequest inValue = new ServiceReference1.GetAgencyGuidAndSetRWACVersionRequest();
            inValue.applicationKeys = applicationKeys;
            return ((ServiceReference1.IRequestService)(this)).GetAgencyGuidAndSetRWACVersionAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetAgencyGUIDResponse> ServiceReference1.IRequestService.GetAgencyGUIDAsync(ServiceReference1.GetAgencyGUIDRequest request)
        {
            return base.Channel.GetAgencyGUIDAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.GetAgencyGUIDResponse> GetAgencyGUIDAsync(ServiceReference1.RockendApplication[] applicationKeys)
        {
            ServiceReference1.GetAgencyGUIDRequest inValue = new ServiceReference1.GetAgencyGUIDRequest();
            inValue.applicationKeys = applicationKeys;
            return ((ServiceReference1.IRequestService)(this)).GetAgencyGUIDAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.UpdateClientSchedulesResponse> ServiceReference1.IRequestService.UpdateClientSchedulesAsync(ServiceReference1.UpdateClientSchedulesRequest request)
        {
            return base.Channel.UpdateClientSchedulesAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.UpdateClientSchedulesResponse> UpdateClientSchedulesAsync(int[] applicationKeys)
        {
            ServiceReference1.UpdateClientSchedulesRequest inValue = new ServiceReference1.UpdateClientSchedulesRequest();
            inValue.applicationKeys = applicationKeys;
            return ((ServiceReference1.IRequestService)(this)).UpdateClientSchedulesAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetProcessorResponse> ServiceReference1.IRequestService.GetProcessorAsync(ServiceReference1.GetProcessorRequest request)
        {
            return base.Channel.GetProcessorAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.GetProcessorResponse> GetProcessorAsync(string assemblyName)
        {
            ServiceReference1.GetProcessorRequest inValue = new ServiceReference1.GetProcessorRequest();
            inValue.assemblyName = assemblyName;
            return ((ServiceReference1.IRequestService)(this)).GetProcessorAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CheckProcessorResponse> ServiceReference1.IRequestService.CheckProcessorAsync(ServiceReference1.CheckProcessorRequest request)
        {
            return base.Channel.CheckProcessorAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.CheckProcessorResponse> CheckProcessorAsync(ServiceReference1.FileCheckRequest request)
        {
            ServiceReference1.CheckProcessorRequest inValue = new ServiceReference1.CheckProcessorRequest();
            inValue.request = request;
            return ((ServiceReference1.IRequestService)(this)).CheckProcessorAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.RegisterAgencyListenerResponse> ServiceReference1.IRequestService.RegisterAgencyListenerAsync(ServiceReference1.RegisterAgencyListenerRequest request)
        {
            return base.Channel.RegisterAgencyListenerAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.RegisterAgencyListenerResponse> RegisterAgencyListenerAsync(ServiceReference1.GetMessageRequest amhListenerRequest)
        {
            ServiceReference1.RegisterAgencyListenerRequest inValue = new ServiceReference1.RegisterAgencyListenerRequest();
            inValue.amhListenerRequest = amhListenerRequest;
            return ((ServiceReference1.IRequestService)(this)).RegisterAgencyListenerAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IRequestService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IRequestService))
            {
                return new System.ServiceModel.EndpointAddress("https://rmh-uat.rockendcommunicator.com.au/requestservice.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RequestServiceClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IRequestService);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RequestServiceClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IRequestService);
        }

        public enum EndpointConfiguration
        {

            WSHttpBinding_IRequestService,
        }
    }
}
